### ISSUE TITLE
Sidebar appears on Sign In pages

### ISSUE THREAD

**Issue by jmhooper** [18F/dolores-landingham-slack-bot#216]
Currently the app has 2 views where the user is in an unauthenticated state:

- The Sign In page (`session/new`)
- The Sign In Error page (`auth/forbidden`)

Both of those views are rendered in the application layout which makes the assumption that the user is signed in and displays the sidebar.

![image](https://cloud.githubusercontent.com/assets/963654/18595877/3c9e9c68-7c0c-11e6-8627-826ecdf3e3ea.png)

![image](https://cloud.githubusercontent.com/assets/963654/18595882/41431bea-7c0c-11e6-8ceb-1195285df7f3.png)

We need to hide the sidebar when the user is not authenticated. A few options:

- render the unauthenticated pages in a different layout
- render them without a layout
- hide the sidebar in the application layout when the user is not signed in

I'm a fan of the first but invite discussion.

For more on this, reference the discussion on #213

**Comment by jessieay** [comment]
Thank you to @JVThomas for submitting a fix for this! 👐
