### ISSUE TITLE
Issue with testing same message to same person

### ISSUE THREAD

**Issue by jessieay** [18F/dolores-landingham-slack-bot#250]
in `app/services/message_sender.rb`, we create a `SentMessage` record for each message sent. This is so that we can record who receives what and when. 

Right now, we validate the uniqueness of the employee id, message id, and message type for each sent message. So, if we try to test the same message to the same employee, that `SentMessage` creation while fail on the second try. 

We do not need to create `SentMessage` records in the testing context. We need to find a way around this.

**Comment by jessieay** [comment]
This issue will also affect onboarding messages

see https://github.com/18F/dolores-landingham-slack-bot/blob/develop/app/services/onboarding_message_employee_matcher.rb#L24 

we only send an onboarding message if there is no `SentMessage` record.

**Comment by jmhooper** [comment]
I'm trying to remember why we need that uniqueness validation. Why do we consider multiple sent messages for an employee / message combination an invalid state?

**Comment by jessieay** [comment]
We use these to determine if someone has already received an onboarding message. I think we can remove the validation *or* just make sure we do not create `SentMessage` records when testing messages

**Comment by jmhooper** [comment]
This was fixed in #255
